def util_function() -> int:
    print("asda")
    print("asda")
    print("asda")
    print("asda")
    print("asda")
    print("asda")
    print("asda")
    print("asda")
    print("asda")
    print("asda")
    print("asda")
    print("asda")
    print("asda")
    print("asda")
    print("asda")
    print("asda")
    print("asda")
    print("asda")

    return 3
