name: Docker Image CI - build and test

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag instance:ci

      - name: Run Tests
        run: |
          docker run instance:ci nox --force-color --session=tests
