name: Build docker image and test on it

on:
  push:
  pull_request:

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag instance:ci

      - name: Run tests
        run: |
          docker run {cookiecutter.package_name}}:ci nox --force-color --session=tests
