name: Tests

on:
  - push
  - pull_request

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag instance:ci

      - name: Run Nox on all sessions
        run: |
          docker run instance:ci nox --force-color

      - name: Upload coverage data
        uses: "actions/upload-artifact@v2.2.4"
        with:
          name: coverage-data
          path: ".cache/.coverage.*"

      - name: Upload documentation
        uses: actions/upload-artifact@v2.2.4
        with:
          name: docs
          path: docs/_build

  coverage:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2.3.4

      - name: Set up Python 3.7
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.7

      - name: Upgrade pip
        run: |
          pip install --constraint=.github/workflows/constraints.txt pip
          pip --version

      - name: Install Nox
        run: |
          pip install --constraint=.github/workflows/constraints.txt nox
          nox --version

      - name: Download coverage data
        uses: actions/download-artifact@v2.0.10
        with:
          name: coverage-data
          path: .cache

      - name: Combine coverage data and display human readable report
        run: |
          nox --force-color --session=coverage

      - name: Create coverage report
        run: |
          nox --force-color --session=coverage -- xml

      - name: Upload coverage report
        uses: codecov/codecov-action@v2.0.2
